Repository NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Server, pull requests merged in 2024-05, with the labels that each got.

#4 [📂File/#3]: 도메인 설정 및 연관관계 매핑
  .gitignore
  build.gradle
  src/main/java/com/joinseminar/yeogieottae/YeogiEottaeApplication.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/model/CompareRoom.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/model/Hotel.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/model/HotelLike.java
  src/main/java/com/joinseminar/yeogieottae/domain/room/model/Room.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/model/RoomLike.java
  src/main/java/com/joinseminar/yeogieottae/domain/user/model/User.java
  src/main/java/com/joinseminar/yeogieottae/global/common/model/BaseEntity.java
Labels: 📂 File

#7 [✨Feat/#6]: Swagger 초기 세팅 및 의존성 추가
  build.gradle
  src/main/java/com/joinseminar/yeogieottae/global/config/SwaggerConfig.java
Labels: 🐶 정교, ✨ Feat

#11 [✨Feat/#9]: 비교하기 > 찜 추가 API & 공통응답 예외처리
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/controller/CompareRoomController.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/controller/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/ComPareRoomRequest.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/repository/CompareRoomRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/repository/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/service/CompareRoomService.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/service/CompareRoomServiceImpl.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/service/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/repository/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/repository/RoomLikeRepository.java
  src/main/java/com/joinseminar/yeogieottae/global/common/dto/ErrorResponse.java
  src/main/java/com/joinseminar/yeogieottae/global/common/dto/SuccessResponse.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/GlobalExceptionHandler.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/ErrorMessage.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/SuccessMessage.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/model/CustomException.java
Labels: 🐶 정교, ✨ Feat

#12 [✨Feat/#10]: 호텔 상세 정보 API 구현
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/controller/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/controller/HotelController.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/dto/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/dto/response/HotelDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/repository/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/repository/HotelRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/service/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/service/HotelService.java
  src/main/java/com/joinseminar/yeogieottae/domain/room/dto/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/room/dto/response/RoomDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/global/common/dto/SuccessResponse.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/GlobalExceptionHandler.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/ErrorMessage.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/SuccessMessage.java
Labels: 🐰 정윤, ✨ Feat

#16 [✨Feat/#15]: 비교하기 > 내가 찜한 객실 목록 조회 API
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/controller/CompareRoomController.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/request/ComPareRoomRequest.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/response/LikedRoomDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/response/LikedRoomListResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/service/CompareRoomService.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/service/CompareRoomServiceImpl.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/repository/RoomLikeRepository.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/SuccessMessage.java
  src/main/resources/db/data.sql
Labels: 🐰 정윤, ✨ Feat

#19 [✨Feat/#17] 찜 목록 조회 API 구현
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/repository/HotelRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/controller/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/controller/HotelLikeController.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/dto/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/dto/response/HotelLikeResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/repository/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/repository/HotelLikeRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/service/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/service/HotelLikeService.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/service/HotelLikeServiceImpl.java
  src/main/java/com/joinseminar/yeogieottae/domain/room/repository/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/room/repository/RoomRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/repository/RoomLikeRepository.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/SuccessMessage.java
Labels: 🐶 정교, ✨ Feat

#20 [✨Feat/#18] 찜(호텔&객실) 추가 API
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/dto/response/HotelDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/repository/HotelLikeRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/room/repository/RoomRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/controller/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/controller/RoomLikeController.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/dto/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/dto/PostHotelOrRoomLikeRequest.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/repository/RoomLikeRepository.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/service/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/service/RoomLikeService.java
  src/main/java/com/joinseminar/yeogieottae/domain/user/repository/Empty
  src/main/java/com/joinseminar/yeogieottae/domain/user/repository/UserRepository.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/ErrorMessage.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/SuccessMessage.java
Labels: 🐰 정윤, ✨ Feat

#22 [✨Feat/#21]: 찜 삭제(취소) API
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/controller/RoomLikeController.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/dto/DeleteHotelOrRoomLikeRequest.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/service/RoomLikeService.java
  src/main/java/com/joinseminar/yeogieottae/global/exception/enums/SuccessMessage.java
Labels: 🐰 정윤, ✨ Feat

#26 [✨Fix/#23] 오류 수정
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/service/HotelLikeServiceImpl.java
Labels: 🐶 정교, 🔨 FIX

#28 [🔨Fix/#27]: request header userId 타입 String으로 수정
  .github/pull_request_template.md
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/controller/CompareRoomController.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotelLike/controller/HotelLikeController.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/controller/RoomLikeController.java
Labels: 🐰 정윤

#31 [🔨Fix/#30]: 모든 API camelcase로 변경
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/response/LikedRoomDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/compareRoom/dto/response/LikedRoomListResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/dto/response/HotelDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/room/dto/response/RoomDetailResponse.java
Labels: 🐰 정윤, 🔨 FIX

#38 [🔨Fix/#37]: 찜 추가 삭제 시 isLiked 필드 상태값 변하도록 수정
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/dto/response/HotelDetailResponse.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/model/Hotel.java
  src/main/java/com/joinseminar/yeogieottae/domain/hotel/service/HotelService.java
  src/main/java/com/joinseminar/yeogieottae/domain/room/model/Room.java
  src/main/java/com/joinseminar/yeogieottae/domain/roomLike/service/RoomLikeService.java
Labels: 🐰 정윤, 🔨 FIX
